kind: Template
apiVersion: v1
objects:
- apiVersion: v1
  data:
    bundles.yml: |
      - name: ansible
        skus:
          - RH00798
          - ESA0016
          - MCT3311
          - MCT3311F3
          - MCT3319
          - MCT3319F3
          - MCT3319RN
          - MCT3319S
          - MCT3320
          - MCT3320F3
          - MCT3320S
          - MCT3321
          - MCT3321F3
          - MCT3321RN
          - MCT3321S
          - MCT3487
          - MCT3487RN
          - MCT3488
          - MCT3488RN
          - MCT3691
          - MCT3691RN
          - MCT3691F3
          - MCT3691F3RN
          - MCT3691S
          - MCT3692
          - MCT3692RN
          - MCT3692F3
          - MCT3692S
          - MCT3693
          - MCT3693F3
          - MCT3693S
          - MCT3694
          - MCT3694RN
          - MCT3694F3
          - MCT3694F3RN
          - MCT3694S
          - MCT3695
          - MCT3695RN
          - MCT3695F3
          - MCT3695F3RN
          - MCT3695S
          - MCT3696
          - MCT3696F3
          - MCT3696S
          - MCT3698
          - MCT3698S
          - MCT3733
          - MCT3733F3
          - MCT3733F3RN
          - MCT3733S
          - MCT3734
          - MCT3742
          - MCT3742F3
          - MCT3742RN
          - MCT3743
          - MCT3743F3
          - MCT3743RN
          - MCT3744
          - MCT3744F3
          - MCT3809
          - MCT3809F3
          - MCT3809F5
          - MCT3810
          - MCT3810F3
          - MCT3810F5
          - MCT3811
          - MCT3811F3
          - MCT3811F5
          - MCT3812
          - MCT3812F3
          - MCT3812F5
          - MCT3813
          - MCT3813F3
          - MCT3813F5
          - MCT3814
          - MCT3814F3
          - MCT3814F5
          - MCT3815
          - MCT3816
          - MCT3817
          - MCT3865
          - MCT3866
          - MCT3866F3
          - MCT3866F3RN
          - MCT3873
          - MCT3873RN
          - MCT3873F3
          - MCT3874
          - MCT3876
          - MCT3876RN
          - MCT3876F3
          - MCT3876S
          - MCT3878
          - MCT3948
          - MCT3948F3
          - MCT4249
          - SER0496
          - SER0497
          - SER0569
          - SER0570
          - SER0764
          - MCT4164
          - MCT4165
          - MCT4164F3
          - MCT4165F3
          - MCT3849
          - MCT3850
          - MCT3991
          - MCT3991F3
          - MCT3991MO
          - MCT3992
          - MCT3992F3
          - MCT3992MO
          - MCT3993
          - MCT3993F3
          - MCT3993MO
          - MCT3994
          - MCT3994F3
          - MCT3994MO
          - MCT3995
          - MCT3995F3
          - MCT3995MO
          - MCT3996
          - MCT3996F3
          - MCT3996MO
          - MCT4019
          - MCT4134
          - MCT4166
          - MCT4166F3
          - MCT4167
          - MCT4167F3
          - MCT4168
          - MCT4168F3
          - MCT4212
          - MCT4212F3
          - MCT4241
          - MCT4391
          - MCT4391F3
          - MCT4392
          - MCT4392F3
          - MCT4522
          - MCT4523
          - MCT4592
          - MCT4592F3
          - MCT4592F5
          - MCT4593
          - MCT4593F3
          - MCT4593F5
          - MCT4594
          - MCT4594F3
          - MCT4594F5
          - MCT4595
          - MCT4595F3
          - MCT4595F5
          - MCT4596
          - MCT4596F3
          - MCT4597
          - MCT4597F3
          - MCT4598
          - MCT4598F3
          - MCT4599
          - MCT4599F3
          - MCT4608
          - MCT4623
          - MCT4623F3
          - MCT4624
          - MCT4624F3
          - MCT4625
          - MCT4625F3
          - MCT4626
          - MCT4626F3
          - MCT4627
          - MCT4627F3
          - MCT4630
          - MCT4630F3
          - MCT4631
          - MCT4631F3
          - MCT4633
          - MCT4633F3
          - MCT4634
          - MCT4634F3
          - MCT4635
          - MCT4635F3
          - MCT4636
          - MCT4636F3
          - MW02049
          - MW02577
          - MW02577F3
          - MW02581
          - MW02581F3
          - RC1257407
          - ES0113909

      - name: cost_management
        use_valid_org_id: true

      - name: insights
        use_valid_org_id: true

      - name: migrations
        use_valid_org_id: true

      - name: subscriptions
        use_valid_org_id: true

      - name: settings
        use_valid_org_id: true

      - name: user_preferences
        use_valid_org_id: true

      - name: smart_management
        skus:
          - SVC3124
          - RH00066
          - RH00065
          - RH00798
          - RH00031
          - RH00031F3
          - RH00032
          - RH00032F3
          - RH00039
          - RH00039F3
          - RH00040
          - RH00040F3

      - name: internal
        use_is_internal: true

      - name: rhods
        skus:
          - MCT4217MO
          - MCT4163

      - name: rhoam
        skus:
          - MW01459
          - MW01460
          - MW01461
          - MW01462
          - MW01737
          - MW01458
          - MW01458MO
          - MW01459
          - MW01459MO
          - MW01460
          - MW01460MO
          - MW01461
          - MW01461MO
          - MW01462
          - MW01462MO
          - MW01737
          - MW01738MO
          - MW01845MO
          - MW01846

      - name: rhosak
        skus:
          - MW01882
          - MW01891
          - MW01892MO
          - MW01891
          - MW01892MO
          - MW01894
          - MW01896MO
          - MW01893
          - MW01895MO

      - name: openshift
        skus:
          - MW00454
          - MW00457F3RN
          - MW00454F3RN
          - MW00454RN
          - MW00457RN
          - MW00457
          - MW00454F3
          - MW00457F3
          - MW00455F3RN
          - MW00455
          - MW00458F3
          - MW00455RN
          - MW00448F3
          - MW00452
          - MW00449S
          - MW00451
          - MW00682
          - MW00451RN
          - MW00371
          - MW00452S
          - MW00451F3
          - MW00449F3
          - MW00452F3
          - MW00991
          - MW00683
          - MW00449
          - MW00450
          - MW00453
          - MW00453F3
          - MW00450F3
          - MW00448
          - MW00448S
          - MW00450RN
          - MW00452RN
          - MW00453S
          - MW00453RN
          - MW00449RN
          - MW00368
          - MW00370F3
          - MW00448F3RN
          - MW00370
          - MW00682MO
          - MW00368F3
          - MW00367F3
          - MW00367
          - MW00460
          - MW00448RN
          - MW00369
          - MW00992
          - MW00450S
          - MW00992RN
          - MW00684
          - MW00371F3
          - MW00451S
          - MW00449F3RN
          - MW00452F3RN
          - MW00463
          - MW00451F3RN
          - MW00461
          - MW00464
          - MW00993
          - MW00376RN
          - MW00377RN
          - MW00374RN
          - MW00688F3
          - MW00375
          - MW00373F3RN
          - MW00378
          - MW00999
          - MW00374S
          - MW00373F3
          - MW00376
          - MW00374
          - MW00373RN
          - MW00997
          - MW00377F3RN
          - MW00376S
          - MW00999RN
          - MW00375RN
          - MW00391
          - MW00393
          - MW00377S
          - MW00377
          - MW00378F3
          - MW00373S
          - MW00374F3
          - MW00392
          - MW00998
          - MW00378RN
          - MW00377F3
          - MW00373
          - MW00376F3
          - MW00375F3
          - MW00376F3RN
          - MW00366
          - MW00362RN
          - MW00365RN
          - MW00365
          - MW00364S
          - MW00365S
          - MW00362F3
          - MW00361RN
          - MW00366F3
          - MW01004
          - MW00382
          - MW00363
          - MW00364
          - MW00364F3
          - MW00681
          - MW00362S
          - MW00362
          - MW00361
          - MW00361S
          - MW00364RN
          - MW00361F3
          - MW00366RN
          - MW00384F3
          - MW00363S
          - MW01002
          - MW00361F3RN
          - MW00382F3
          - MW00362F3RN
          - MW00364F3RN
          - MW00365F3
          - MW00363RN
          - MW00679MO
          - MW00380
          - MW00379RN
          - MW01007
          - MW01003
          - MW01003RN
          - MW00366S
          - MW00680
          - MW00363F3RN
          - MW01006
          - MW00679
          - MW00363F3
          - MW00379
          - MW00383F3
          - MW00381
          - MW00365F3RN
          - MW01007RN
          - MW01257
          - MW01255
          - MW01329RN
          - MW01258
          - MW01254
          - MW01257F3
          - MW01254F3
          - MW01329
          - MW01263
          - MW01286
          - MW01260
          - MW01267
          - MW01270
          - MW01266
          - MW01271
          - MW01268
          - MW01269
          - MCT3009
          - MW01008
          - MW00329RN
          - MCT3265
          - MCT2735F3RN
          - MCT3016
          - MW00330
          - MW00329F3
          - MW00329
          - MW00594HR
          - MW00331F3
          - ESA0012
          - MCT2863
          - MW01382
          - MW01502
          - MCT3264
          - MCT2862F3
          - MW00330RN
          - MW00210HR
          - MCT3266
          - MCT3756
          - MCT2862S
          - MCT3156
          - MCT3753
          - MCT3753F3
          - MW00211HR
          - MCT3263
          - MCT2863F3
          - MW00227
          - MW00332
          - MW00332F3
          - MCT3754
          - MW01009
          - MW01463F3
          - MCT3479F3
          - MW00421RN
          - MCT2736
          - MW00226
          - MCT2735S
          - MCT2735RN
          - MCT3010
          - MCT3754F3
          - MCT3268
          - MCT3818
          - MCT2863RN
          - MCT2735F3
          - MCT2736F3
          - MW00226MO
          - MCT2862RN
          - MCT2736RN
          - MCT2862
          - MW00331
          - MCT2736S
          - MW00335
          - MW00472F3
          - MCT3819F5
          - MCT2735
          - MW00330F3
          - MW00330S
          - MCT3760F3
          - MW00422
          - MW01743
          - MCT2863S
          - MW00329F3RN
          - MW00331RN
          - MW00421F3
          - MW01744
          - MW01501F3
          - MW01502F3
          - MW01246
          - MW01739
          - MCT3755
          - MCT3479
          - MW00421
          - MW00335RN
          - MW01383
          - MCT3579RN
          - MW00419F3
          - MCT3579
          - MW01247
          - MW00332RN
          - MCT3760
          - MCT3478S
          - MW00332S
          - SER0423
          - MW01615
          - MW00595
          - MCT3479S
          - MCT2862F3RN
          - MCT2738
          - MW00227F3
          - MW00501
          - MW01320
          - MCT3477F3
          - MW00785F3
          - MW00782F3
          - MCT3478F3RN
          - MCT3754S
          - MW01965
          - MCT3754RN
          - MCT3489S
          - MW02031MO
          - MW01951MO
          - SER0620
          - MW01482F3
          - MW01853
          - MW00334
          - MW02055
          - MCT3754F3RN
          - MW00210MO
          - MCT3477RN
          - MCT3753RN
          - MCT3753F3RN
          - MCT3492
          - MCT3491
          - MCT2863F3RN
          - MCT3156RN
          - MCT3477
          - MCT3818F3
          - MW01849
          - MW01482
          - MCT3819
          - MW01501
          - MCT3581RN
          - MW00782
          - MW00331S
          - MCT3819F3
          - MW00336
          - MW00331F3RN
          - MW01465F3
          - MW01309
          - MW01463
          - MW00783F3
          - MCT3819S
          - MCT3580
          - MW00422F5
          - MW01740
          - MW02045HR
          - MCT3489
          - MCT2658
          - MW01245
          - MCT3758
          - MW01615F3
          - MW01382S
          - MW00333
          - MW00329S
          - MW00472
          - MW00419
          - MW01009RN
          - MW01950MO
          - MW00330F3RN
          - MW00226F3
          - MW01741
          - MCT2956
          - MCT3820
          - MCT3478
          - MCT3478F3
          - MCT3581F3
          - MW01018
          - MW01742
          - MCT2737
          - MCT3479RN
          - MW00336RN
          - MW01507
          - MW00421F5
          - MW01316
          - MCT3759
          - MW01398
          - MCT3580RN
          - MW01019
          - MW01008RN
          - MCT3581
          - MCT3490
          - MCT3476F3
          - ESA0019
          - MW01507F3
          - MW01988
          - MCT2736F3RN
          - MW00783
          - MW00422F3
          - MCT3818F5
          - MW01241HR
          - MCT3478RN
          - MW00419F5
          - MW00788

      - name: rhel
        use_valid_org_id: true

      - name: acs
        skus:
          - MW02162
          - MW02162RN
          - MW02162S
          - MW02162F3
          - MW02162F3RN
          - MW02159
          - MW02159RN
          - MW02159S
          - MW02159F3
          - MW02159F3RN
          - MW02164HR
          - MW02161HR
          - MW02163MO
          - MW02160MO
          - MW02165
          - MW02165RN
          - MW02165S
          - MW02165MO
          - MW02165F3
          - MW02165F3RN
          - MW02166
          - MW02166RN
          - MW02166S
          - MW02166MO
          - MW02166F3
          - MW02166F3RN
          - MW02167
          - MW02167RN
          - MW02167S
          - MW02167HR
          - MW02167MO
          - MW02167F3
          - MW02167F3RN
          - MW02291
          - MW02291RN
          - MW02291S
          - MW02291F3
          - MW02291F3RN
          - MW02404
          - MW02404RN
          - MW02404S
          - MW02404HR
          - MW02404MO
          - MW02404F3
          - MW02404F3RN
          - MW02405
          - MW02405RN
          - MW02405S
          - MW02405HR
          - MW02405MO
          - MW02405F3
          - MW02405F3RN
          - SER0774
          - SER0795
          - SER0798

  kind: ConfigMap
  metadata:
    creationTimestamp: null
    name: entitlements-config
    annotations:
      qontract.recycle: "true"
