kind: Template
apiVersion: v1
objects:
- apiVersion: v1
  data:
    bundles.yml: |
      - name: ansible
        skus:
          RH00798:
              is_trial: false
          ESA0016:
              is_trial: false
          MCT3319:
              is_trial: false
          MCT3319F3:
              is_trial: false
          MCT3319RN:
              is_trial: false
          MCT3319S:
              is_trial: false
          MCT3320:
              is_trial: false
          MCT3320F3:
              is_trial: false
          MCT3320RN:
              is_trial: false
          MCT3320S:
              is_trial: false
          MCT3321:
              is_trial: false
          MCT3321F3:
              is_trial: false
          MCT3321RN:
              is_trial: false
          MCT3321S:
              is_trial: false
          MCT3487:
              is_trial: false
          MCT3487F3:
              is_trial: false
          MCT3487RN:
              is_trial: false
          MCT3487S:
              is_trial: false
          MCT3488:
              is_trial: false
          MCT3488F3:
              is_trial: false
          MCT3488RN:
              is_trial: false
          MCT3488S:
              is_trial: false
          MCT3685:
              is_trial: false
          MCT3685RN:
              is_trial: false
          MCT3685F3:
              is_trial: false
          MCT3685F3RN:
              is_trial: false
          MCT3685S:
              is_trial: false
          MCT3691:
              is_trial: false
          MCT3691RN:
              is_trial: false
          MCT3691F3:
              is_trial: false
          MCT3691F3RN:
              is_trial: false
          MCT3691S:
              is_trial: false
          MCT3692:
              is_trial: false
          MCT3692RN:
              is_trial: false
          MCT3692F3:
              is_trial: false
          MCT3692F3RN:
              is_trial: false
          MCT3692S:
              is_trial: false
          MCT3693:
              is_trial: false
          MCT3693RN:
              is_trial: false
          MCT3693F3:
              is_trial: false
          MCT3693F3RN:
              is_trial: false
          MCT3693S:
              is_trial: false
          MCT3694:
              is_trial: false
          MCT3694RN:
              is_trial: false
          MCT3694F3:
              is_trial: false
          MCT3694F3RN:
              is_trial: false
          MCT3694S:
              is_trial: false
          MCT3695:
              is_trial: false
          MCT3695RN:
              is_trial: false
          MCT3695F3:
              is_trial: false
          MCT3695F3RN:
              is_trial: false
          MCT3695S:
              is_trial: false
          MCT3696:
              is_trial: false
          MCT3696RN:
              is_trial: false
          MCT3696F3:
              is_trial: false
          MCT3696F3RN:
              is_trial: false
          MCT3696S:
              is_trial: false
          MCT3698:
              is_trial: false
          MCT3698RN:
              is_trial: false
          MCT3698F3:
              is_trial: false
          MCT3698F3RN:
              is_trial: false
          MCT3698S:
              is_trial: false
          MCT3733:
              is_trial: false
          MCT3733RN:
              is_trial: false
          MCT3733F3:
              is_trial: false
          MCT3733F3RN:
              is_trial: false
          MCT3733S:
              is_trial: false
          MCT3734:
              is_trial: false
          MCT3734RN:
              is_trial: false
          MCT3734F3:
              is_trial: false
          MCT3734F3RN:
              is_trial: false
          MCT3734S:
              is_trial: false
          MCT3735:
              is_trial: false
          MCT3735RN:
              is_trial: false
          MCT3735F3:
              is_trial: false
          MCT3735F3RN:
              is_trial: false
          MCT3735S:
              is_trial: false
          MCT3742:
              is_trial: false
          MCT3742F3:
              is_trial: false
          MCT3742RN:
              is_trial: false
          MCT3742S:
              is_trial: false
          MCT3743:
              is_trial: false
          MCT3743F3:
              is_trial: false
          MCT3743RN:
              is_trial: false
          MCT3743S:
              is_trial: false
          MCT3744:
              is_trial: false
          MCT3744F3:
              is_trial: false
          MCT3744RN:
              is_trial: false
          MCT3744S:
              is_trial: false
          MCT3809:
              is_trial: false
          MCT3809RN:
              is_trial: false
          MCT3809F3:
              is_trial: false
          MCT3809F3RN:
              is_trial: false
          MCT3809S:
              is_trial: false
          MCT3810:
              is_trial: false
          MCT3810RN:
              is_trial: false
          MCT3810F3:
              is_trial: false
          MCT3810F3RN:
              is_trial: false
          MCT3810S:
              is_trial: false
          MCT3811:
              is_trial: false
          MCT3811RN:
              is_trial: false
          MCT3811F3:
              is_trial: false
          MCT3811F3RN:
              is_trial: false
          MCT3811S:
              is_trial: false
          MCT3812:
              is_trial: false
          MCT3812RN:
              is_trial: false
          MCT3812F3:
              is_trial: false
          MCT3812F3RN:
              is_trial: false
          MCT3812S:
              is_trial: false
          MCT3813:
              is_trial: false
          MCT3813RN:
              is_trial: false
          MCT3813F3:
              is_trial: false
          MCT3813F3RN:
              is_trial: false
          MCT3813S:
              is_trial: false
          MCT3814:
              is_trial: false
          MCT3814RN:
              is_trial: false
          MCT3814F3:
              is_trial: false
          MCT3814F3RN:
              is_trial: false
          MCT3815S:
              is_trial: false
          MCT3815:
              is_trial: false
          MCT3815RN:
              is_trial: false
          MCT3815F3:
              is_trial: false
          MCT3815F3RN:
              is_trial: false
          MCT3816:
              is_trial: false
          MCT3816RN:
              is_trial: false
          MCT3816F3:
              is_trial: false
          MCT3816F3RN:
              is_trial: false
          MCT3816S:
              is_trial: false
          MCT3817:
              is_trial: false
          MCT3817RN:
              is_trial: false
          MCT3817F3:
              is_trial: false
          MCT3817F3RN:
              is_trial: false
          MCT3817S:
              is_trial: false
          MCT3865:
              is_trial: false
          MCT3865RN:
              is_trial: false
          MCT3865F3:
              is_trial: false
          MCT3865F3RN:
              is_trial: false
          MCT3865S:
              is_trial: false
          MCT3866:
              is_trial: false
          MCT3866RN:
              is_trial: false
          MCT3866F3:
              is_trial: false
          MCT3866F3RN:
              is_trial: false
          MCT3866S:
              is_trial: false
          MCT3873:
              is_trial: false
          MCT3873RN:
              is_trial: false
          MCT3873F3:
              is_trial: false
          MCT3873F3RN:
              is_trial: false
          MCT3873S:
              is_trial: false
          MCT3874:
              is_trial: false
          MCT3874RN:
              is_trial: false
          MCT3874F3:
              is_trial: false
          MCT3874F3RN:
              is_trial: false
          MCT3874S:
              is_trial: false
          MCT3875:
              is_trial: false
          MCT3875RN:
              is_trial: false
          MCT3875F3:
              is_trial: false
          MCT3875F3RN:
              is_trial: false
          MCT3875S:
              is_trial: false
          MCT3876:
              is_trial: false
          MCT3876RN:
              is_trial: false
          MCT3876F3:
              is_trial: false
          MCT3876F3RN:
              is_trial: false
          MCT3876S:
              is_trial: false
          MCT3877:
              is_trial: false
          MCT3877RN:
              is_trial: false
          MCT3877F3:
              is_trial: false
          MCT3877F3RN:
              is_trial: false
          MCT3877S:
              is_trial: false
          MCT3878:
              is_trial: false
          MCT3878RN:
              is_trial: false
          MCT3878F3:
              is_trial: false
          MCT3878F3RN:
              is_trial: false
          MCT3878S:
              is_trial: false
          MCT3906:
              is_trial: false
          MCT3906RN:
              is_trial: false
          MCT3906F3:
              is_trial: false
          MCT3906F3RN:
              is_trial: false
          MCT3906S:
              is_trial: false
          MCT3907:
              is_trial: false
          MCT3907RN:
              is_trial: false
          MCT3907F3:
              is_trial: false
          MCT3907F3RN:
              is_trial: false
          MCT3907S:
              is_trial: false
          MCT3908:
              is_trial: false
          MCT3908RN:
              is_trial: false
          MCT3908F3:
              is_trial: false
          MCT3908F3RN:
              is_trial: false
          MCT3908S:
              is_trial: false
          MCT3909:
              is_trial: false
          MCT3909RN:
              is_trial: false
          MCT3909F3:
              is_trial: false
          MCT3909F3RN:
              is_trial: false
          MCT3909S:
              is_trial: false
          MCT3910:
              is_trial: false
          MCT3910RN:
              is_trial: false
          MCT3910F3:
              is_trial: false
          MCT3910F3RN:
              is_trial: false
          MCT3910S:
              is_trial: false
          MCT3911:
              is_trial: false
          MCT3911RN:
              is_trial: false
          MCT3911F3:
              is_trial: false
          MCT3911F3RN:
              is_trial: false
          MCT3911S:
              is_trial: false
          MCT3948:
              is_trial: false
          MW01882:
              is_trial: false
          SER0496:
              is_trial: true
          SER0497:
              is_trial: true
          SER0569:
              is_trial: true
          SER0570:
              is_trial: true
          SER0574:
              is_trial: true

      - name: cost_management
        use_valid_acc_num: true

      - name: insights
        use_valid_acc_num: true

      - name: migrations
        use_valid_acc_num: true

      - name: subscriptions
        use_valid_acc_num: true

      - name: settings
        use_valid_acc_num: true

      - name: user_preferences
        use_valid_acc_num: true

      - name: openshift
        use_valid_acc_num: false

      - name: smart_management
        skus:
          SVC3124:
              is_trial: false
          RH00066:
              is_trial: true
          RH00065:
              is_trial: true
          RH00798:
              is_trial: false

      - name: internal
        use_is_internal: true
        
      - name: rhel
        use_valid_acc_num: true

      - name: rhods
        skus:
          MCT4217MO:
            is_trial: false
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    name: entitlements-config
    annotations:
      qontract.recycle: "true"
